databases:
  - name: mysite
    databaseName: mysite_igsh
    user: mysite

services:
  - type: web
    name: mysite
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn mysite.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: mysite_igsh
          property: postgres://mysite:6R4SltwS4wDFwUon9uNlWPSrJ1qYtfkT@dpg-ca8jp5r0tnutcided9mg-a/mysite_igsh
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
