# Generated by Django 3.0.8 on 2022-05-27 19:24

from django.db import migrations, models
import django_extensions.db.fields
import render.storage


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Art',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paid', models.DecimalField(decimal_places=2, default='0.0', max_digits=10, null=True)),
                ('log_number', models.CharField(blank=True, max_length=10, null=True)),
                ('medium', models.CharField(blank=True, max_length=255, null=True)),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='title')),
                ('description', models.TextField(blank=True, max_length=5000, null=True)),
                ('image', models.ImageField(max_length=255, null=True, storage=render.storage.SpacesStorage(), upload_to='images/')),
                ('style', models.CharField(blank=True, max_length=255, null=True)),
                ('size', models.CharField(blank=True, max_length=255, null=True)),
                ('art_location', models.TextField(blank=True, max_length=1000)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('available', models.NullBooleanField(default=True)),
                ('country', models.CharField(default='USA', max_length=255, null=True)),
                ('show', models.CharField(blank=True, max_length=255, null=True)),
                ('artist', models.CharField(default='Jonathan Green', max_length=255, null=True)),
                ('certificate', models.NullBooleanField(default=False)),
                ('condition', models.CharField(blank=True, max_length=255, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('notes', models.TextField(blank=True, max_length=5000)),
                ('value', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('signature', models.CharField(blank=True, max_length=255, null=True)),
                ('gift', models.NullBooleanField(default=False)),
                ('year_span', models.CharField(blank=True, max_length=255, null=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('paper', models.CharField(blank=True, max_length=255, null=True)),
                ('in_progress', models.NullBooleanField(default=False)),
            ],
        ),
    ]
