# Generated by Django 4.0.4 on 2022-05-28 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('render', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='art',
            name='available',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='art',
            name='certificate',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='art',
            name='gift',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='art',
            name='in_progress',
            field=models.BooleanField(null=True),
        ),
    ]
