# Generated by Django 3.0.8 on 2022-06-06 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('render', '0002_alter_art_available_alter_art_certificate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='art',
            name='condition',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
    ]
