# Generated by Django 3.0.8 on 2022-06-06 13:54

from django.db import migrations, models
import django_extensions.db.fields
import render.storage


class Migration(migrations.Migration):

    dependencies = [
        ('render', '0003_auto_20220606_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='art',
            name='image',
            field=models.ImageField(max_length=512, null=True, storage=render.storage.SpacesStorage(), upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='art',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, max_length=255, populate_from='title'),
        ),
    ]
